default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: photogur_development

test:
  <<: *default
  database: photogur_test

production:
  <<: *default
  database: photogur_production
  username: photogur
  password: <%= ENV['PHOTOGUR_DATABASE_PASSWORD'] %>
