default: &default
  adapter: postgresql
  encoding: unicode

  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: photogur_dev

test:
  <<: *default
  database: photogur_test


production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { 'photogur_production' } %>

